// =========== SIGNUP ============

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

// =============== LOGIN =================

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// ============ FETCH SINGLE USER ===========

export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

// ============ EDIT SINGLE USER ===========

export const EDIT_USER_START = "EDIT_USER_START";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";

// ============ BLOCK USER ===========

export const BLOCK_USER_FAILURE = "BLOCK_USER_FAILURE ";
export const BLOCK_USER_START = "BLOCK_USER_START";
export const BLOCK_USER_SUCCESS = " BLOCK_USER_SUCCESS";

// ============ FETCH REVIEW LIST ===========

export const FETCH_REVIEWS_START = "FETCH_REVIEWS_START";
export const FETCH_REVIEWS_SUCCESS = "FETCH_REVIEWS_SUCCESS";
export const FETCH_REVIEWS_FAILURE = "FETCH_REVIEWS_FAILURE";

// ============ FETCH REVIEW BY ID ===========

export const FETCH_REVIEW_BY_ID_START = "FETCH_REVIEW_BY_ID_START";
export const FETCH_REVIEW_BY_ID_SUCCESS = "FETCH_REVIEW_BY_ID_SUCCESS";
export const FETCH_REVIEW_BY_ID_FAILURE = "FETCH_REVIEW_BY_ID_FAILURE";

// ============ POST REVIEW ===========

export const POST_REVIEW_START = "POST_REVIEW_START";
export const POST_REVIEW_SUCCESS = "POST_REVIEW_SUCCESS";
export const POST_REVIEW_FAILURE = "POST_REVIEW_FAILURE";

// ============ EDIT REVIEW ===========
export const EDIT_REVIEW_START = "EDIT_REVIEW_START";
export const EDIT_REVIEW_SUCCESS = "EDIT_REVIEW_SUCCESS";
export const EDIT_REVIEW_FAILURE = "EDIT_REVIEW_FAILURE";

// ============ DELETE REVIEW ===========
export const DELETE_REVIEW_START = "DELETE_REVIEW_START";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAILURE = "DELETE_REVIEW_FAILURE";

// ============ GET COMPANY ===========

export const FETCH_COMPANIES_START = "FETCH_COMPANIES_START";
export const FETCH_COMPANIES_SUCCESS = "FETCH_COMPANIES_SUCCESS";
export const FETCH_COMPANIES_FAILURE = "FETCH_COMPANIES_FAILURE";

// ============ POST COMPANY ===========

export const POST_COMPANY_START = "POST_COMPANY_START";
export const POST_COMPANY_SUCCESS = "POST_COMPANY_SUCCESS";
export const POST_COMPANY_FAILURE = "POST_COMPANY_FAILURE";
